version: '3'

services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: frontend
        ports:
            - "3000:3000"
        volumes:
            - '/usr/app/node_modules'
            - './frontend:/usr/app'
        # links:
        #     - "rmitify-service"

