version: '3'

services:
  redis:
    image: redis:6.0.3-alpine
    container_name: "my_redis"
    ports:
      - "6379:6379"
    restart: always     # "unless-stopped" or "always"
      #    ## UNCOMMENT THESE LINES IF WE USE CUSTOM REDIS CONFIG ##
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  app:
    build: ./Backend_Redis_messaging
    ports:
      - "9000:10091"
  frontend:
    build: ./DuyMessagingFrontend/
    ports:
      - "3000:3000"
