version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: tc
      POSTGRES_USER: tc
      POSTGRES_PASSWORD: tc
  appdb:
    build:
      context: ./MessagingBackendPostgre
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/tc
      SPRING_DATASOURCE_USERNAME: tc
      SPRING_DATASOURCE_PASSWORD: tc
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.0.3-alpine
    ports:
      - "6379:6379"
    restart: always     # "unless-stopped" or "always"
    #    ## UNCOMMENT THESE LINES IF WE USE CUSTOM REDIS CONFIG ##
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  appredis:
    build: ./MessagingBackendRedis
    ports:
      - "10091:10091"
    depends_on:
      - redis
      - db
    links:
      - redis
  frontend:
    build: ./Frontend
    ports:
    - "3000:3000"